Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.synced_folder "~/git/recount-pump", "/home/vagrant/git/recount-pump"
  config.vm.synced_folder "~/git/recount-unify", "/home/vagrant/git/recount-unify"

  config.vm.provision "shell", privileged: true, name: "update", inline: <<-SHELL
    apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
  SHELL

  config.vm.provision "shell", privileged: true, name: "install docker and singularity", inline: <<-SHELL
    printf "deb http://httpredir.debian.org/debian stretch-backports main non-free\ndeb-src http://httpredir.debian.org/debian stretch-backports main non-free" > /etc/apt/sources.list.d/backports.list
    apt-get update -y && apt-get install -y apt-transport-https dirmngr
    echo 'deb https://apt.dockerproject.org/repo debian-stretch main' >> /etc/apt/sources.list
    apt-get update -y && apt-get install -y --allow-unauthenticated docker-engine
     apt-get install -y libarchive-dev squashfs-tools graphviz && \
        apt-get -t stretch-backports install singularity-container
  SHELL

  config.vm.provision "shell", privileged: true, name: "install python", inline: <<-SHELL
    apt-get install -y python python-pip
  SHELL

  config.vm.provision "shell", privileged: true, name: "upgrade pip", inline: <<-SHELL
    pip install --upgrade pip
  SHELL
  
  # TODO: allow vagrant user to use docker
end
