Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian9"
  config.vm.synced_folder "~/git/recount-pump", "/home/vagrant/git/recount-pump"
  config.vm.synced_folder "~/git/recount-pump", "/home/vagrant/git/recount-pump"
  config.vm.synced_folder "~/.recount",         "/home/vagrant/.recount"
  config.vm.synced_folder "~/.aws",             "/home/vagrant/.aws"
  config.vm.synced_folder "~/.ssh_ec2",         "/home/vagrant/.ssh_ec2"
  config.vm.provision "file", source: "~/.docker/creds.txt",           destination: "/home/vagrant/.docker/creds.txt"
  config.vm.provision "file", source: "~/.docker/quay_creds.txt",      destination: "/home/vagrant/.docker/quay_creds.txt"
  config.vm.provision "file", source: "~/.docker/dockerhub_creds.txt", destination: "/home/vagrant/.docker/dockerhub_creds.txt"

  config.vm.provision "shell", privileged: true, name: "update", inline: <<-SHELL
    apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
  SHELL

  config.vm.provision "shell", privileged: true, name: "install docker and singularity", inline: <<-SHELL
    printf "deb http://httpredir.debian.org/debian stretch-backports main non-free\ndeb-src http://httpredir.debian.org/debian stretch-backports main non-free" > /etc/apt/sources.list.d/backports.list
    apt-get update -y && apt-get install -y apt-transport-https dirmngr
    echo 'deb https://apt.dockerproject.org/repo debian-stretch main' >> /etc/apt/sources.list
    apt-get update -y && apt-get install -y --allow-unauthenticated docker-engine
     apt-get install -y libarchive-dev squashfs-tools graphviz && \
        apt-get -t stretch-backports install singularity-container
    usermod -a -G docker vagrant
  SHELL

  config.vm.provision "shell", privileged: true, name: "install docker-compose", inline: <<-SHELL
      curl -s -L https://github.com/docker/compose/releases/download/1.22.0-rc1/docker-compose-$(uname -s)-$(uname -m) \
          -o /usr/bin/docker-compose
      chmod +x /usr/bin/docker-compose
  SHELL

  config.vm.provision "shell", privileged: true, name: "install python", inline: <<-SHELL
    apt-get install -y python python-pip
  SHELL

  config.vm.provision "shell", privileged: true, name: "upgrade pip", inline: <<-SHELL
    pip install --upgrade pip
  SHELL

  config.vm.provision "shell", privileged: true, name: "install vagrant", inline: <<-SHELL
    VER=2.0.4
    FN=vagrant_${VER}_x86_64.deb
    wget --quiet -O ${FN} https://releases.hashicorp.com/vagrant/${VER}/${FN}
    dpkg -i ${FN}
    rm -f ${FN}
  SHELL
  
  config.vm.provision "shell", privileged: false, name: "install vagrant plugin", inline: <<-SHELL
    vagrant plugin install vagrant-aws-mkubenka --plugin-version "0.7.2.pre.22"
    vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
  SHELL
  
  config.vm.provision "shell", privileged: false, name: "install python mods", inline: <<-SHELL
    sudo pip install -r ~/git/recount-pump/vagrant/recount-dev/requirements.txt
  SHELL
end
