language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install --upgrade pip setuptools
- pip install -r requirements.txt
script:
- ./unit_test.sh
notifications:
  slack:
    secure: Bfb64Y4/B5x7DUdpvNN2cl56qE9FQ6kJxU7HpYDjgER6Bj/kUs64S1DkLmh2L2B0oNL/Lm/FWjTyreZdv5X3/cf51bgeKX9dZIjjPusUmtuYhMHj7tysbnIdAqKon/9E106wBnZZCdY6529vyzht5YdLyIcM7cQ7zBKq85NJ+5dGIQms3yUcApnBgjl746r5dsjIZo1P4Hn8AEmg1r3aDoW3Mo3vh4KM/ZcnA5AAoHyaLNM/stj3jFK7I9b/zsq7I2baRhdh15/vg6veO88FeB1yxtfdyEg+lEK8xOddpjOIR/pOW+3Jdfu84y5QaFYDRZKMgMOm0Yo1t3BTYyPtIZpLU1rAfIR77xU5+Oobu3UMSn7W4ANDqLy+JpivvRMfLUcCtvtQlcIwLNGN9KQNlKHRbnEIwiU99em8pdwYcRxNyLjMEQyqFzbfAH9XEmqeD4sideFEZjKY9lmk/5BGRsbRXUrep8D1Ri/8gOew/gJ9Ahwdme8XXajcIYPfknUMglxQAGfGcQxihdQXZ7PRW9FzYxtbM+WLmYTdftyHwD+LcyCyqPdiAlaeBnwIiLinDXdavN6O7thdNbe8Jt0yuS2zYZI2Fx2FpEbqgVxQ+p4eDj2kE6s4vM/wx/SEXaYKxNzChxfrw+Y3NTtWQ3clDW9dVvt18zSzlm18hfXX14w=
