version: '3'
services:
  q:
    image: "rabbitmq:3.7"
    ports:
      - "15672:15672"
      - "5672:5672"
  s3:
    image: "benlangmead/recount-minio"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
  db:
    image: "postgres:10.4"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: recount
      POSTGRES_PASSWORD: recount-postgres
      POSTGRES_DB: recount-test
  recount:
    build: .
    depends_on:
      - "q"
      - "s3"
      - "db"
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      RECOUNT_TEST_DB: postgres://recount:recount-postgres@db:5432/recount-test
      RECOUNT_TEST_Q: q:5672
      RECOUNT_TEST_S3: http://s3:9000
    command: >
      bash -c "./wait-for-it.sh db:5432 --
                 ./wait-for-it.sh s3:9000 --
                   ./wait-for-it.sh q:5672 --
                     echo '*** STARTING ***' &&
                     py.test -rv src/*.py src/*/*.py &&
                     echo '*** SUCCESS ***'"
