version: '3'
services:
  elasticmq:
    image: "softwaremill/elasticmq:0.14.4"
    container_name: "elasticmq"
    volumes:
      - ./docker/elasticmq/custom-compose.conf:/opt/elasticmq.conf
    ports:
      - "29324:9324"
  s3:
    image: "quay.io/benlangmead/recount-minio"
    container_name: "recount-minio"
    ports:
      - "29000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
  db:
    image: "postgres:10.4"
    container_name: "postgres-recount"
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: recount
      POSTGRES_PASSWORD: recount-postgres
      POSTGRES_DB: recount-test
  recount:
    image: "quay.io/benlangmead/recount-pump"
    container_name: "recount"
    depends_on:
      - "elasticmq"
      - "s3"
      - "db"
    privileged: true
    cap_add:
      - SYS_ADMIN
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      RECOUNT_TEST_DB: postgres://recount:recount-postgres@db:5432/recount-test
      RECOUNT_TEST_Q: http://elasticmq:9324
      RECOUNT_TEST_S3: http://s3:9000
      RECOUNT_IMAGES: /images
      SINGULARITY_CACHEDIR: /images
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./creds/.mc:/creds/.mc
      - ./creds/.aws:/creds/.aws
      - ./creds/.recount:/creds/.recount
      - ./testing/images:/images
      - ./testing/output:/output
      - ./testing/temp:/temporary
    command: /code/test_entry.sh
