version: '3'
services:
  elasticmq:
    image: "softwaremill/elasticmq:0.14.6"
    container_name: "elasticmq"
    volumes:
      - ./docker/elasticmq/custom-compose.conf:/opt/elasticmq.conf
    ports:
      - "29324:9324"
  s3:
    image: "quay.io/benlangmead/recount-minio"
    container_name: "recount-minio"
    ports:
      - "29000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
  db:
    image: "postgres:10.4"
    container_name: "postgres-recount"
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: recount
      POSTGRES_PASSWORD: recount-postgres
      POSTGRES_DB: recount-test
