# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'

Vagrant.configure("2") do |config|

    config.vm.box = "dummy"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :aws do |aws, override|
        aws.region = "us-east-1"
        aws.ami = "ami-13401669"
        aws.tags = { 'Application' => 'docker' }
        aws.instance_type = 'c4.2xlarge'
        aws.keypair_name = "default"
        aws.subnet_id = "subnet-1fc8de7a"
        aws.security_groups = ["sg-16845a6e"]
        aws.associate_public_ip = true

        aws.block_device_mapping = [{
            'DeviceName' => "/dev/sdf",
            'VirtualName' => "ephemeral0",
            'Ebs.VolumeSize' => 100,
            'Ebs.DeleteOnTermination' => true,
            'Ebs.VolumeType' => 'gp2'
        }]

        override.ssh.username = "ec2-user"
        override.ssh.private_key_path = "~/.ec2_jhu/default.pem"
    end

    ssh_key_path = "~/.ssh/"
    config.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa' }", destination: "~ec2-user/.ssh/id_rsa"
    config.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa.pub' }", destination: "~ec2-user/.ssh/id_rsa.pub"
    config.vm.provision "file", source: "~/.synapseConfig", destination: "~ec2-user/.synapseConfig"
    config.vm.provision "file", source: "~/.docker/creds.txt", destination: "~ec2-user/.docker/creds.txt"

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        if [ ! -d /work ] ; then
            mkfs -t ext4 /dev/xvdf
            mkdir /work
            mount /dev/xvdf /work/
            chmod a+w /work
        fi
        yum -y install emacs-nox git wget gcc g++

        if ! which singularity ; then
        
            # The TACC version of singularity is 2.3.1
            
            VER=2.3.1
            wget https://github.com/singularityware/singularity/releases/download/$VER/singularity-$VER.tar.gz
            tar xvf singularity-$VER.tar.gz
            cd singularity-$VER
            ./configure --prefix=/usr/local --sysconfdir=/etc
            make && make install
            cd ..
        fi
        
        ! which pip && wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py
        ! which synapse && /usr/local/bin/pip install synapseclient
        ! which globus && /usr/local/bin/pip install globus-cli
    SHELL
    
    config.vm.provision "shell", privileged: false, inline: <<-SHELL
        # How do I control *which* user this is?  Want it to be ec2-user
        echo "Host github.com" > ~/.ssh/config
        echo "  HostName github.com" >> ~/.ssh/config
        echo "  User git" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        chmod go-rwx ~/.ssh/config
        
        PROJ="recount-pump"
        IMAGE="benlangmead/recount-pump"
        
        cd /work
        git clone git@github.com:langmead-lab/${PROJ}.git
        cd ${PROJ}/nextflow
        
        docker login -u `cut -d' ' -f1 ~/.docker/creds.txt` \
                     -p `cut -d' ' -f2 ~/.docker/creds.txt`
        
        docker pull ${IMAGE}
        ./docker_build.sh
        docker push ${IMAGE}
        
        ./singularity_convert.sh
    SHELL
end
