# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrant plugin install vagrant-aws-mkubenka --plugin-version "0.7.2.pre.22"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'
REGION = "us-east-2"
INSTANCE_TYPE = "c4.xlarge"
BID_PRICE = "0.06"
ACCOUNT = "jhu-langmead"
KEYPAIR = "recount-jhu-us-east-2"

Vagrant.configure("2") do |config|

    config.vm.box = "dummy"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :aws do |aws, override|
        aws.aws_dir = ENV['HOME'] + "/.aws/"
        aws.aws_profile = ACCOUNT
        aws.region = REGION
        aws.tags = { 'Application' => 'recount' }
        aws.instance_type = INSTANCE_TYPE
        aws.associate_public_ip = true
        aws.keypair_name = KEYPAIR
        if REGION == "us-east-1"
            aws.ami = "ami-0ff8a91507f77f867"
            aws.subnet_id = "subnet-1fc8de7a"
            aws.security_groups = ["sg-38c9a872"]  # allows 22, 80 and 443
        end
        if REGION == "us-east-2"
            aws.ami = "ami-0b59bfac6be064b78"
            if ACCOUNT == "default"
                aws.subnet_id = "subnet-09923c0ca7212a423"
                aws.security_groups = ["sg-051ff8479e318f0ab"]  # allows just 22
            else
                aws.subnet_id = "subnet-03dc5fea763057c7d"
                aws.security_groups = ["sg-0a01b0edfa261cb34"]  # allows just 22
            end
        end
        aws.block_device_mapping = [{
            'DeviceName' => "/dev/sdf",
            'VirtualName' => "ephemeral0",
            'Ebs.VolumeSize' => 100,
            'Ebs.DeleteOnTermination' => true,
            'Ebs.VolumeType' => 'gp2'
        }]
        override.ssh.username = "ec2-user"
        override.ssh.private_key_path = "~/.aws/" + KEYPAIR + ".pem"
        aws.region_config REGION do |region|
            region.spot_instance = true
            region.spot_max_price = BID_PRICE
        end
    end

    config.vm.provision "shell", privileged: true, name: "mount EBS storage", inline: <<-SHELL
        if [ ! -d /work ] ; then
            mkfs -q -t ext4 /dev/xvdf
            mkdir /work
            mount /dev/xvdf /work/
            chmod a+w /work
        fi
    SHELL

    config.vm.provision "shell", privileged: true, name: "install Linux packages", inline: <<-SHELL
        yum install -q -y git gcc g++ aws-cli libarchive-devel squashfs-tools
    SHELL

    config.vm.provision "shell", privileged: true, name: "install docker", inline: <<-SHELL
        yum install -q -y docker
        mkdir /work/docker
        sed -i 's/^OPTIONS=.*//' /etc/sysconfig/docker
        echo 'OPTIONS="--default-ulimit nofile=1024:4096 -g /work/docker"' >> /etc/sysconfig/docker
        service docker start
    SHELL

    config.vm.provision "file", source: "~/.ssh/id_rsa",       destination: "~/.ssh/id_rsa"
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub",   destination: "~/.ssh/id_rsa.pub"
    config.vm.provision "file", source: "~/.docker/creds.txt", destination: "~/.docker/creds.txt"
    config.vm.provision "file", source: "~/.aws/credentials",  destination: "~/.aws/credentials"
    config.vm.provision "file", source: "~/.aws/config",       destination: "~/.aws/config"

    config.vm.provision "shell", privileged: true, name: "move home dir files over", inline: <<-SHELL
        for i in ssh docker aws ; do
            mkdir -p ~/.${i}
            mv ~ec2-user/.${i}/* ~/.${i}/
            chown root ~/.${i}/*
            chmod go-rwx ~/.${i}/*
        done
    SHELL

    config.vm.provision "shell", privileged: true, name: "install docker-compose", inline: <<-SHELL
        echo "Install docker-compose"
        curl -s -L https://github.com/docker/compose/releases/download/1.22.0-rc1/docker-compose-$(uname -s)-$(uname -m) \
            -o /usr/bin/docker-compose
        chmod +x /usr/bin/docker-compose
    SHELL
        
    config.vm.provision "shell", privileged: true, name: "install Singularity", inline: <<-SHELL
        SINGVER="2.5.2"
        echo "Install Singualrity"
        wget -q https://github.com/singularityware/singularity/releases/download/${SINGVER}/singularity-${SINGVER}.tar.gz
        tar xf singularity-${SINGVER}.tar.gz
        cd singularity-${SINGVER} && \
            ./configure --prefix=/usr > /dev/null && \
            make > /dev/null && make install > /dev/null && \
            cd .. && \
            rm -rf singularity-${SINGVER} singularity-${SINGVER}.tar.gz
    SHELL

    config.vm.provision "shell", privileged: true, name: "install watchtower", inline: <<-SHELL
        pip install watchtower==0.5.2
        pip install docopt==0.6.2
    SHELL
    
    config.vm.provision "shell", privileged: true, name: "setup ssh for git", inline: <<-SHELL
        echo "Host github.com"               > /root/.ssh/config
        echo "  HostName github.com"        >> /root/.ssh/config
        echo "  User git"                   >> /root/.ssh/config
        echo "  IdentityFile ~/.ssh/id_rsa" >> /root/.ssh/config
        echo "  StrictHostKeyChecking no"   >> /root/.ssh/config
        chmod go-rwx /root/.ssh/config
    SHELL

    config.vm.provision "shell", privileged: true, name: "clone recount", inline: <<-SHELL
        cd /work && git clone -q git@github.com:langmead-lab/recount-pump.git
    SHELL
        
    config.vm.provision "shell", privileged: true, name: "docker login", inline: <<-SHELL
        docker login quay.io -u $(cut -d' ' -f1 /root/.docker/creds.txt) \
                             -p $(cut -d' ' -f2 /root/.docker/creds.txt)
    SHELL

    config.vm.provision "shell", privileged: true, name: "recount-pump image", inline: <<-SHELL
        SKIP_BUILD=0
        if [ ${SKIP_BUILD} = 0 ] ; then
            cd /work/recount-pump && ./build.sh && ./push.sh
            if [ $? -eq 0 ] ; then
                echo "===HAPPY benlangmead/recount-pump built and pushed"
            else
                echo "===SAD ERROR building and/or pushing benlangmead/recount-pump"
            fi
        fi
    SHELL

    config.vm.provision "shell", privileged: true, name: "write cluster.ini", inline: <<-SHELL
        mkdir -p /root/.recount
        
        echo "[cluster]"                                            > /root/.recount/cluster_docker.ini
        echo "system = docker"                                     >> /root/.recount/cluster_docker.ini
        echo "ref_base = /work/recount-ref"                        >> /root/.recount/cluster_docker.ini
        echo "temp_base = /work/recount-temp-docker/temp"          >> /root/.recount/cluster_docker.ini
        echo "input_base = /work/recount-temp-docker/input"        >> /root/.recount/cluster_docker.ini
        echo "output_base = /work/recount-temp-docker/output"      >> /root/.recount/cluster_docker.ini
        echo "ref_mount = /container-mounts/recount/ref"           >> /root/.recount/cluster_docker.ini
        echo "temp_mount = /container-mounts/recount/temp"         >> /root/.recount/cluster_docker.ini
        echo "input_mount = /container-mounts/recount/input"       >> /root/.recount/cluster_docker.ini
        echo "output_mount = /container-mounts/recount/output"     >> /root/.recount/cluster_docker.ini

        echo "[cluster]"                                            > /root/.recount/cluster_singularity.ini
        echo "system = singularity"                                >> /root/.recount/cluster_singularity.ini
        echo "ref_base = /work/recount-ref"                        >> /root/.recount/cluster_singularity.ini
        echo "temp_base = /work/recount-temp-singularity/temp"     >> /root/.recount/cluster_singularity.ini
        echo "input_base = /work/recount-temp-singularity/input"   >> /root/.recount/cluster_singularity.ini
        echo "output_base = /work/recount-temp-singularity/output" >> /root/.recount/cluster_singularity.ini
        echo "ref_mount = /container-mounts/recount/ref"           >> /root/.recount/cluster_singularity.ini
        echo "temp_mount = /container-mounts/recount/temp"         >> /root/.recount/cluster_singularity.ini
        echo "input_mount = /container-mounts/recount/input"       >> /root/.recount/cluster_singularity.ini
        echo "output_mount = /container-mounts/recount/output"     >> /root/.recount/cluster_singularity.ini
    SHELL

    config.vm.provision "shell", privileged: true, name: "analysis images", inline: <<-SHELL
        FLOWBASE="/work/recount-pump/workflow"
        export RECOUNT_REF=/work/recount-ref
        mkdir -p ${RECOUNT_REF}
        cd ${RECOUNT_REF} && ${FLOWBASE}/prep_test.sh
        SKIP_BUILD=0
        for FLOW in rs1 ; do
            FLOWDIR="${FLOWBASE}/${FLOW}"
            IMAGE=$(cat ${FLOWDIR}/image.txt)

            echo "******************************************************"
            echo "Processing workflow: \"${FLOW}\""
            echo "              image: \"${IMAGE}\""
            echo "******************************************************"

            if [ ${SKIP_BUILD} = 0 ] ; then
                echo "------------------------------------------------------"
                echo "Building and pushing (\"$FLOW\")"
                echo "------------------------------------------------------"
                cd ${FLOWDIR} && ../common/build.sh && ../common/push.sh
                if [ $? -eq 0 ] ; then
                    echo "===HAPPY ${IMAGE} built and pushed"
                else
                    echo "===SAD ERROR building and/or pushing ${IMAGE}"
                fi
            fi

            echo "------------------------------------------------------"
            echo "Test-running Docker (\"$FLOW\")"
            echo "------------------------------------------------------"
            cd ${FLOWDIR} && ../../src/run.py \
                --input ../common/accessions.txt \
                --image ${IMAGE} \
                --ini /root/.recount/cluster_docker.ini \
                --name docker-test-${FLOW}
            if [ $? -eq 0 ] ; then
                echo "===HAPPY ${IMAGE} ran in Docker"
            else
                echo "===SAD ERROR running ${IMAGE} in Docker"
            fi
            #find /work/recount-temp-docker/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
            #cat ${FLOWDIR}/outmd5.txt
            rm -rf /work/recount-temp-docker/temp
            rm -rf /work/recount-temp-docker/input
            rm -rf /work/recount-temp-docker/output

            echo "------------------------------------------------------"
            echo "Test-running Singularity (\"$FLOW\")"
            echo "------------------------------------------------------"
            cd ${FLOWDIR} && ../../src/run.py \
                --input ../common/accessions.txt \
                --image docker://${IMAGE} \
                --ini /root/.recount/cluster_singularity.ini \
                --name singularity-test-${FLOW}
            if [ $? -eq 0 ] ; then
                echo "===HAPPY ${IMAGE} ran in Singularity"
            else
                echo "===SAD ERROR running ${IMAGE} in Singularity"
            fi
            #find /work/recount-temp-singularity/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
            #cat ${FLOWDIR}/outmd5.txt
            rm -rf /work/recount-temp-singularity/temp
            rm -rf /work/recount-temp-singularity/input
            rm -rf /work/recount-temp-singularity/output
        done
    SHELL

    config.vm.provision "shell", privileged: true, name: "minio image", inline: <<-SHELL
        cd /work/recount-pump/docker/minio && ./build.sh && ./push.sh
        if [ $? -eq 0 ] ; then
            echo "===HAPPY benlangmead/recount-minio built and pushed"
        else
            echo "===SAD ERROR building and/or pushing benlangmead/recount-minio"
        fi
    SHELL

    config.vm.provision "shell", privileged: true, name: "integration test", inline: <<-SHELL
        if [ -n "$(which docker-compose)" -a -x "$(which docker-compose)" ] ; then
            cd /work/recount-pump && ./integration_test.sh
            if [ $? -eq 0 ] ; then
                echo "===HAPPY integration tests passed"
            else
                echo "===SAD one or more integrations tests FAILED"
            fi
        else
            echo "ERROR No docker-compose!!!" && exit 1
        fi
    SHELL
end
