# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrant plugin install vagrant-aws

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'

REGION = "us-east-1"

Vagrant.configure("2") do |config|

    config.vm.box = "dummy"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :aws do |aws, override|
        aws.region = REGION
        aws.ami = "ami-13401669"
        aws.tags = { 'Application' => 'docker' }
        aws.instance_type = "c4.xlarge"
        aws.keypair_name = "default"
        aws.subnet_id = "subnet-1fc8de7a"
        aws.security_groups = ["sg-16845a6e"]
        aws.associate_public_ip = true
        aws.block_device_mapping = [{
            'DeviceName' => "/dev/sdf",
            'VirtualName' => "ephemeral0",
            'Ebs.VolumeSize' => 100,
            'Ebs.DeleteOnTermination' => true,
            'Ebs.VolumeType' => 'gp2'
        }]
        override.ssh.username = "ec2-user"
        override.ssh.private_key_path = "~/.ec2_jhu/default.pem"
        aws.region_config REGION do |region|
            region.spot_instance = true
            region.spot_max_price = "0.06"
        end
    end

    config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~ec2-user/.ssh/id_rsa"
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~ec2-user/.ssh/id_rsa.pub"
    config.vm.provision "file", source: "~/.docker/creds.txt", destination: "~ec2-user/.docker/creds.txt"
    config.vm.provision "file", source: "~/.aws/credentials", destination: "~ec2-user/.aws/credentials"
    config.vm.provision "file", source: "~/.aws/config", destination: "~ec2-user/.aws/config"

    config.vm.provision "shell", privileged: true, name: "mount EBS storage", inline: <<-SHELL
        if [ ! -d /work ] ; then
            mkfs -q -t ext4 /dev/xvdf
            mkdir /work
            mount /dev/xvdf /work/
            chmod a+w /work
        fi
    SHELL

    config.vm.provision "shell", privileged: true, name: "install Linux packages", inline: <<-SHELL
        sleep 5
        killall yum
        yum install -y git wget gcc g++ aws-cli libarchive-devel squashfs-tools
    SHELL
         
    config.vm.provision "shell", privileged: true, name: "install docker-compose", inline: <<-SHELL
        echo "Install docker-compose"
        curl -s -L https://github.com/docker/compose/releases/download/1.22.0-rc1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
    SHELL
        
    config.vm.provision "shell", privileged: false, name: "install Singularity", inline: <<-SHELL
        SINGVER="2.5.2"
        echo "Install Singualrity"
        wget -q https://github.com/singularityware/singularity/releases/download/${SINGVER}/singularity-${SINGVER}.tar.gz
        tar xf singularity-${SINGVER}.tar.gz
        cd singularity-${SINGVER} && \
            ./configure --prefix=/usr/local > /dev/null && \
            make > /dev/null && sudo make install > /dev/null && \
            cd .. && \
            rm -rf singularity-${SINGVER} singularity-${SINGVER}.tar.gz
    SHELL
    
    config.vm.provision "shell", privileged: false, name: "setup ssh for git", inline: <<-SHELL
        echo "Host github.com" > ~/.ssh/config
        echo "  HostName github.com" >> ~/.ssh/config
        echo "  User git" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        chmod go-rwx ~/.ssh/config
    SHELL

    config.vm.provision "shell", privileged: false, name: "clone recount", inline: <<-SHELL
        cd /work && git clone -q git@github.com:langmead-lab/recount-pump.git
    SHELL
        
    config.vm.provision "shell", privileged: false, name: "docker login", inline: <<-SHELL
        docker login quay.io -u $(cut -d' ' -f1 ~/.docker/creds.txt) \
                             -p $(cut -d' ' -f2 ~/.docker/creds.txt)
    SHELL

    config.vm.provision "shell", privileged: false, name: "recount-pump image", inline: <<-SHELL
        SKIP_BUILD=0
        if [ ${SKIP_BUILD} = 0 ] ; then
            cd /work/recount-pump && ./build.sh && ./push.sh
            if [ $? -eq 0 ] ; then
                echo "===HAPPY benlangmead/recount-pump built and pushed"
            else
                echo "===SAD ERROR building and/or pushing benlangmead/recount-pump"
            fi
        fi
    SHELL

    config.vm.provision "shell", privileged: false, name: "write cluster.ini", inline: <<-SHELL
        mkdir -p ~/.recount
        
        echo "[cluster]"                                            > ~/.recount/cluster_docker.ini
        echo "system = docker"                                     >> ~/.recount/cluster_docker.ini
        echo "ref_base = /work/recount-ref"                        >> ~/.recount/cluster_docker.ini
        echo "temp_base = /work/recount-temp-docker/temp"          >> ~/.recount/cluster_docker.ini
        echo "input_base = /work/recount-temp-docker/input"        >> ~/.recount/cluster_docker.ini
        echo "output_base = /work/recount-temp-docker/output"      >> ~/.recount/cluster_docker.ini
        echo "ref_mount = /container-mounts/recount/ref"           >> ~/.recount/cluster_docker.ini
        echo "temp_mount = /container-mounts/recount/temp"         >> ~/.recount/cluster_docker.ini
        echo "input_mount = /container-mounts/recount/input"       >> ~/.recount/cluster_docker.ini
        echo "output_mount = /container-mounts/recount/output"     >> ~/.recount/cluster_docker.ini

        echo "[cluster]"                                            > ~/.recount/cluster_singularity.ini
        echo "system = singularity"                                >> ~/.recount/cluster_singularity.ini
        echo "ref_base = /work/recount-ref"                        >> ~/.recount/cluster_singularity.ini
        echo "temp_base = /work/recount-temp-singularity/temp"     >> ~/.recount/cluster_singularity.ini
        echo "input_base = /work/recount-temp-singularity/input"   >> ~/.recount/cluster_singularity.ini
        echo "output_base = /work/recount-temp-singularity/output" >> ~/.recount/cluster_singularity.ini
        echo "ref_mount = /container-mounts/recount/ref"           >> ~/.recount/cluster_singularity.ini
        echo "temp_mount = /container-mounts/recount/temp"         >> ~/.recount/cluster_singularity.ini
        echo "input_mount = /container-mounts/recount/input"       >> ~/.recount/cluster_singularity.ini
        echo "output_mount = /container-mounts/recount/output"     >> ~/.recount/cluster_singularity.ini
    SHELL

    config.vm.provision "shell", privileged: false, name: "analysis images", inline: <<-SHELL
        FLOWBASE="/work/recount-pump/workflow"
        export RECOUNT_REF=/work/recount-ref
        mkdir -p ${RECOUNT_REF}
        cd ${RECOUNT_REF} && ${FLOWBASE}/prep_test.sh
        SKIP_BUILD=0
        for FLOW in rna-seq-lite-nf ; do
            FLOWDIR="${FLOWBASE}/${FLOW}"
            IMAGE=$(cat ${FLOWDIR}/image.txt)

            echo "******************************************************"
            echo "Processing workflow: \"${FLOW}\""
            echo "              image: \"${IMAGE}\""
            echo "******************************************************"

            if [ ${SKIP_BUILD} = 0 ] ; then
                echo "------------------------------------------------------"
                echo "Building and pushing (\"$FLOW\")"
                echo "------------------------------------------------------"
                cd ${FLOWDIR} && ../common/build.sh && ../common/push.sh
                if [ $? -eq 0 ] ; then
                    echo "===HAPPY ${IMAGE} built and pushed"
                else
                    echo "===SAD ERROR building and/or pushing ${IMAGE}"
                fi
            fi

            echo "------------------------------------------------------"
            echo "Test-running Docker (\"$FLOW\")"
            echo "------------------------------------------------------"
            cd ${FLOWDIR} && ../common/run.py \
                --input ../common/accessions.txt \
                --image ${IMAGE} \
                --ini ~/.recount/cluster_docker.ini \
                --name docker-test
            if [ $? -eq 0 ] ; then
                echo "===HAPPY ${IMAGE} ran in Docker"
            else
                echo "===SAD ERROR running ${IMAGE} in Docker"
            fi
            find /work/recount-temp-docker/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
            cat ${FLOWDIR}/outmd5.txt

            echo "------------------------------------------------------"
            echo "Test-running Singularity (\"$FLOW\")"
            echo "------------------------------------------------------"
            cd ${FLOWDIR} && ../common/run.py \
                --input ../common/accessions.txt \
                --image docker://${IMAGE} \
                --ini ~/.recount/cluster_singularity.ini \
                --name singularity-test
            if [ $? -eq 0 ] ; then
                echo "===HAPPY ${IMAGE} ran in Singularity"
            else
                echo "===SAD ERROR running ${IMAGE} in Singularity"
            fi
            find /work/recount-temp-singularity/output -type f -exec md5sum {} ";" | sort | md5sum | awk '{print $1}'
            cat ${FLOWDIR}/outmd5.txt
        done
    SHELL

    config.vm.provision "shell", privileged: false, name: "minio image", inline: <<-SHELL
        cd /work/recount-pump/docker/minio && ./build.sh && ./push.sh
        if [ $? -eq 0 ] ; then
            echo "===HAPPY benlangmead/recount-minio built and pushed"
        else
            echo "===SAD ERROR building and/or pushing benlangmead/recount-minio"
        fi
    SHELL

    config.vm.provision "shell", privileged: false, name: "integration test", inline: <<-SHELL
        cd /work/recount-pump && ./integration_test.sh
        if [ $? -eq 0 ] ; then
            echo "===HAPPY integration tests passed"
        else
            echo "===SAD one or more integrations tests FAILED"
        fi
    SHELL
end
