#FROM quay.io/broadsword/recount-pump:1.0.6
FROM quay.io/broadsword/recount-pump:1.1.2

USER root
WORKDIR /

#RUN wget -q https://github.com/NCI-GDC/gdc-client/releases/download/1.5.0/gdc-client_v1.5.0_Ubuntu_x64.zip && \
ENV GDC_VER=1.6.1
RUN wget -q https://gdc.cancer.gov/files/public/file/gdc-client_v${GDC_VER}_Ubuntu_x64.zip && \
    unzip gdc-client_v${GDC_VER}_Ubuntu_x64.zip && \
    mv gdc-client /usr/bin && \
    rm -f gdc-client_v${GDC_VER}_Ubuntu_x64.zip

# install Snakefile
COPY Snakefile /Snakefile
RUN chmod a+r /Snakefile

# install generic workflow wrapper script
COPY workflow.bash /workflow.bash
RUN chmod a+rx /workflow.bash

# install download.sh
COPY download.sh /download.sh
RUN chmod a+r /download.sh

COPY entrypoint.sh /entrypoint.sh
RUN chmod a+rx /entrypoint.sh

USER recount
WORKDIR /home/recount/

ENTRYPOINT ["bash", "-c", "/entrypoint.sh"]
