FROM quay.io/broadsword/recount-pump:1.0.6

USER root

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    chmod a+x ./aws/install && \
    ./aws/install

WORKDIR /
RUN wget "https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.0.0/sratoolkit.3.0.0-ubuntu64.tar.gz" && \
    tar -zxvf sratoolkit.3.0.0-ubuntu64.tar.gz && \
    ln -fs /sratoolkit.3.0.0-ubuntu64 /sratoolkit

# install Snakefile
COPY Snakefile /Snakefile
RUN chmod a+r /Snakefile

# install generic workflow wrapper script
COPY workflow.bash /workflow.bash
RUN chmod a+rx /workflow.bash

# install download.sh
COPY download.sh /download.sh
RUN chmod a+r /download.sh

COPY entrypoint.sh /entrypoint.sh
RUN chmod a+rx /entrypoint.sh

RUN mkdir -p /home/recount/.ncbi
COPY user-settings.3_0_0.mkfg /home/recount/.ncbi/user-settings.mkfg

USER recount
WORKDIR /home/recount/

ENTRYPOINT ["bash", "-c", "/entrypoint.sh"]
